#------------------------------------------------------------
# This is a RasPiMouse_with_MRPT document build actions
#
# Noriaki Ando <Noriaki.Ando@gmail.com>
# 2020.08.27
#------------------------------------------------------------

name: sphinx-build

# Build runs when push or pull request to the master branch happened
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# main jobs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out
      - uses: actions/checkout@v2

      # Sphinx document build on docker
      - name: build-sphinx
        run: |
          sudo docker run --rm -v $GITHUB_WORKSPACE/doc:/docs sphinxdoc/sphinx make html
      
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
#          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./doc/html

